sudo: required

stages:
- ubuntu-16.04
- ubuntu-18.04

services:
- docker

jobs: 
  include:
  - stage: ubuntu-16.04
    script:
    - id=`docker run -d -e CI=true -v $(pwd):/sysinit ubuntu:16.04 bash -i /sysinit/start.sh`
    - docker attach $id
  - stage: ubuntu-18.04
    script:
    - id=`docker run -d -e CI=true -v $(pwd):/sysinit ubuntu:18.04 bash -i /sysinit/start.sh`
    - docker attach $id
