sudo: required

stages:
- ubuntu-20.04

services:
- docker

jobs: 
  include:
  - stage: ubuntu-20.04
    script:
    - id=`docker run -d -e CI=true -v $(pwd):/sysinit ubuntu:20.04 bash -c "cd /sysinit && ./start.sh"`
    - docker attach $id
